name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set HOME environment variable
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        $env:HOME = $env:HOMEPATH
        echo "$HOME"
    - name: Run tests
      run: cargo test
