name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  schedule:  # at 03:06 on day-of-month 5
    - cron: '6 3 5 * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust-version: ['1.77.2', '1.86.0']

    steps:
    - uses: actions/checkout@v4
    - name: Setup Rust
      uses: moonrepo/setup-rust@v1
      with:
        channel: ${{ matrix.rust-version }}
    - name: Run tests on Windows after setting HOME environment variable
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        $env:HOME = $env:HOMEPATH
        echo "$HOME"
        rustc --version
        cargo test
    - name: Run tests on POSIX
      run: |
        rustc --version
        cargo test
      if: ${{ matrix.os != 'windows-latest' }}
